name: AbbyCrerie
favicon: null
layout_spectrum: 0.1311821029521525
typography_spectrum: 0.19518394023180008
title: Abby Crerie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090607'
    - '#413628'
    - '#9f6c3b'
    - '#8c98a4'
    - '#ffffff'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
